Lesson 02
BadAllOff/react-thinknetica-first-app pull request #4
Opened 2020-07-26 14:25 UTC by BadAllOff

2020-07-26 14:33 UTC, BadAllOff commented
Nолько что заметил что я ветки попутал немного. Но начиная с  Shamil Add: header - это то что нужно.

2020-07-26 17:17 UTC, index01d requested changes

2020-07-26 17:17 UTC, index01d commented on .gitignore
> +package-lock.json
lock файл лучше оставить в репозитории. Он нужен, чтобы точно синхронизировать версии зависимостей между пользователями

2020-07-26 17:17 UTC, index01d commented on src/AuthorList.js
> +    const showBtnText = `Show all ` + authors.length + ` Authors`;
интересно что конкатенация реализована с помощью оператора `+`, хотя используются шаблонные строки, где можно было бы написать `Show all ${authors.length} Authors`

2020-07-26 17:17 UTC, index01d commented on src/AuthorList.js
> +    const visibleAuthors = authors.filter(function (a, index) {
здесь можно было бы использовать `slice(0, 3)` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

```js
const numOfAuthorsToShow = showAllAuthors ? authors.length : 3;
const authorsToShow = authors.slice(0, numOfAuthorsToShow);
```
и ниже
```js
{ showAllAuthors ? `Show all ${authors.length} Authors` : 'Hide authors' }
```

2020-07-27 07:28 UTC, BadAllOff commented on .gitignore
> +package-lock.json
ок. я убрал его из-за проблем во время мерга после параллельной разработки в двух ветках. Версии вроде записаны в package файле, думал это работает так же как бандлер в Рельсах и можно его просто воссоздавать.

2020-07-27 07:29 UTC, BadAllOff commented on src/AuthorList.js
> +    const showBtnText = `Show all ` + authors.length + ` Authors`;
блин.... призраки старого JS ещё в голове.))

2020-07-27 15:11 UTC, index01d requested changes

2020-07-27 15:11 UTC, index01d commented on src/AuthorList.js
> +  // Таким образом всё становиться наглядно уже в "заголовке" функции
Получился антипаттерн - длинная цепочка вызовов. Вывод в зависимости от условия должен был остаться в render-функции родительского компонента. А ShowAllButton можно было выделить в отдельный компонент.

2020-07-27 15:11 UTC, index01d commented on src/AuthorList.js
> +  // Таким образом всё становиться наглядно уже в "заголовке" функции
Попробуй выделить компонент, а я поправлю, если что-то пойдёт не так

2020-07-29 13:10 UTC, index01d requested changes

2020-07-29 13:10 UTC, index01d commented on src/AuthorList.js
> +          authors={authors}
достаточно передать количество авторов.

2020-07-29 13:10 UTC, index01d commented on src/ShowAuthorsBtn.js
> +                onClick={() => {
Достаточно было `onClick={this.props.toggleShowAll}`

2020-07-29 13:10 UTC, index01d commented on src/ShowAuthorsBtn.js
> +  toggleBtn() {
метод не выглядит нужным

2020-07-29 13:10 UTC, index01d commented on src/ShowAuthorsBtn.js
> +        {authors.length > 3 && (
это условие логичнее было бы оставить в компоненте списка, тогда здесь не потребовалось бы фрагмента

2020-07-31 11:36 UTC, BadAllOff commented on src/AuthorList.js
> +          authors={authors}
Тут я на будущее оставил все данные, вдруг если придётся еще что-то добавлять. В целом, "оставить на будущее вдруг понадобится" - у меня довольно частое явление поэтому буду рад комментариям на эту тему (уверен я не один такой). :)) Глядя в прошлое могу сказать что иногда это минус, иногда было в тему и помогало. Тут согласен что минус, слишком мал функционал у кнопки что бы целую коллекцию передавать. читающего код может запутать.

2020-07-31 11:40 UTC, BadAllOff commented on src/ShowAuthorsBtn.js
> +  toggleBtn() {
тут я пытался избежать использования this.props... в JSX. Это вроде как улучшает читаемость.

2020-08-01 08:14 UTC, index01d approved these changes

2020-08-01 12:27 UTC, merged