Lesson o3
BadAllOff/react-thinknetica-first-app pull request #5
Opened 2020-08-01 18:27 UTC by BadAllOff

2020-08-01 19:50 UTC, index01d requested changes
Предлагаю сгруппировать модули компонентов по директориям: 

`src/components/BookCard/`
`src/components/AuthorCard`
`src/components/Layout`
`src/components/Feedback`

2020-08-01 19:50 UTC, index01d commented on src/ContactFormModal.js
> +                    <form onSubmit={this.handleSubmit}>
саму форму можно было бы сделать отдельным компонентом

2020-08-01 19:52 UTC, index01d requested changes

2020-08-01 19:52 UTC, index01d commented on src/ContactFormModal.js
> +                        <label>Email address</label>
можно выделить компонент Field со следующим интерфейсом:

```js
  <Field 
    label='Email address' 
    hint='We'll never share your email with anyone else.'
    type='email' 
    value={this.state.email} 
    name='email' 
    onChange={this.handleChange}
 />
```

2020-08-02 13:32 UTC, BadAllOff commented
> `src/components/Feedback`

а для чего Фидбек папка? Если для контактной формы, не будет ли логичнее в папку с компонентом автора? (там, как я понимаю, прямая зависимость. Если нет автора - не должно быть и формы).

2020-08-03 15:01 UTC, index01d commented
> > `src/components/Feedback`
> 
> а для чего Фидбек папка? Если для контактной формы, не будет ли логичнее в папку с компонентом автора? (там, как я понимаю, прямая зависимость. Если нет автора - не должно быть и формы).

в теории можно и так, да. я скорее про принцип, чем про конкретный вариант

2020-08-03 15:05 UTC, index01d approved these changes

2020-08-03 15:05 UTC, index01d commented on src/components/BookCard/BookCard.js
>  class BookCard extends React.Component {
выглядит так, что в этом компоненте также можно было бы выделить компонент
`<Row label='Pages count'>{book.page_count} pages</Row>`

2020-08-04 12:26 UTC, merged