Lesson 05
BadAllOff/react-thinknetica-first-app pull request #7
Opened 2020-08-08 22:06 UTC by BadAllOff

2020-08-08 22:08 UTC, BadAllOff commented
После Merge branch 'lesson_04' :)

2020-08-10 11:43 UTC, index01d requested changes
По файловой структуре начнём последовательно перерабатывать:
1) App лучше разместить в корне `src/` или `src/components`, его назначение - быть главным компонентом
2) Из `App` вынесем `Layout/index.js`, который будет содержать в себе заголовок и подвал
Тогда в App останется 
```js
import Layout from './Layout'; // здесь index подставится сам
...
<Layout>
  <SimilarBooksList similarBooks={this.props.similarBooks} />
  <BookContainer books={this.props.books} />
</Layout>
```

3) similarBooks.json и books.json пока нужно убрать из основного проекта (можно продолжить использовать в тестах), компонент SimilarBooks можно пока спрятать, к нему ещё вернёмся. На данном этапе мы больше не будем брать данные для основного приложения из статики

4) Можно разделить зависимости BookList и BookCard (про BookCard оставил заметку в Review): 
```
Book/
  Card/
    Тут все компоненты карточки книги
  List/
    Тут все компоненты списка
```

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/AuthorCommission.js
> +      user_offer: this.props.book.min_price,
в проекте принято именовать ключи camelCase'ом. snake_case выбивается из общего стиля и читать код становится сложнее

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/AuthorCommission.js
> +    let authors_revenue = ((value / 100) * 90).toFixed(2);
если здесь выделить комиссию
```
const comission = 0.1;
const convertedPrice = sourcePrice * (1 - comission) ^ 1)
```
то разница будет только в степени `^1` или `^(-1)`
```js
const power = direction === 'to' ? 1 : -1;
const comission = 0.1;
const convertedPrice = sourcePrice * (1 - comission) ^ power)
```

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/AuthorCommission.js
> +    if (user_offer >= min_price) {
опрятнее было бы обойтись без условия `userOffer: Math.max(minPrice, userOffer)`

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/AuthorCommission.js
> +    let user_offer = value;
?

2020-08-10 11:43 UTC, index01d commented on src/components/BookContainer/BookContainer.js
> +          books: books,
можно просто `this.setState({ books })`

2020-08-10 11:43 UTC, index01d commented on src/components/BookContainer/BookContainer.js
> +  _mapFromAirtable({ records }) {
стоило бы сразу сделать структуру с camelCase'ом, чтобы в проекте все идентификаторы именовались в одном стиле

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/BookCard.js
>      const isBestseller = book.subscribers_count > 50 ? true : false;
тернарный оператор тут явно лишний

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/BookCard.js
> +        {book.author_listlength != 0 && (
похоже на опечатку.

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/BookCard.js
>      const { book } = this.props;
чтобы не дублировать `book.` можно сразу деструктурировать параметры
`const { book: { authors, pageCount, language, progress, ... } } = this.props`

2020-08-10 11:43 UTC, index01d commented on src/components/BookCard/BookDetailsModal.js
> +    const authorNames = book.author_list
не первый раз встречаю этот код, возможно стоит выделить компонент `<JoinedList delimiter=',' list={authors} valueKey='name' />`

2020-08-10 11:43 UTC, index01d commented on src/components/BookContainer/BookContainer.js
> +            for (let i = 0; i < record.fields.authors.length; i++) {
Чуть-чуть более высокоуровнево можно было бы написать с использованием библиотеки lodash (https://lodash.com/docs/4.17.15#zipObject):
```js
_.zip(
  fields["id (from authors)"],
  fields["name (from authors)"],
  fields["about (from authors)"],
  fields["avatar (from authors)"].map(item => item.url)
).map(record => _.zipObject(
  ['id', 'name', 'about', 'avatar'],
  record
))

```

2020-08-11 11:21 UTC, merged

2020-08-11 14:30 UTC, BadAllOff commented on src/components/BookCard/AuthorCommission.js
> +    let authors_revenue = ((value / 100) * 90).toFixed(2);
Я не понимаю как работает эта формула в джаваскрипте.
 Почему 
`((sourcePrice * (1 - comission)) ** power) ` не работает а 
`((sourcePrice * (1 - comission)) ^ power) ` работает но даёт только целые числа.
И почему работает `((sourcePrice * (1 - comission)) * power)`?

И почему при попытке двигать ползунок клавишами сумма постоянно только убывает... 
Я в полном конфузе если честно.

2020-08-11 14:58 UTC, BadAllOff commented on src/components/BookCard/AuthorCommission.js
> +    let user_offer = value;
Это вычисление для прибыли автора. В данном коде в аргумент value передавалос значение из рендж-элемента предложения пользователя. Уже объединил в одну функцию, этого не будет в коде.

2020-08-15 13:00 UTC, BadAllOff commented on src/components/BookCard/BookDetailsModal.js
> +    const authorNames = book.author_list
изщменил код. компонент не понадобился.